### ISSUE TITLE
Subir archivos de configuración

### ISSUE THREAD

**Issue by fefulowe** [FlisolCaba/flisolator#1]
Falta subir los archivos de configuración. Probablemente convenga asignar una carpeta a para cada uno de los nodos (node0, node1, o n1, n2, n3) donde ubicar los archivos según la funcionalidad del nodo.

**Comment by HacKanCuBa** [comment]
Están así nomás extraidos del root en https://github.com/FlisolCaba/flisolator/releases
La idea era acomodarlos... y escribir los instructivos

**Comment by fefulowe** [comment]
Exactamente. Estaban en https://github.com/FlisolCaba/flisolator/releases/tag/v1.0 . Cierro el issue.
